//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kladionica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oklada
    {
        public long OkladaId { get; set; }
        public long PonudaId { get; set; }
        public long ListicId { get; set; }
        public double Koeficient { get; set; }
    
        public virtual Listic Listic { get; set; }
        public virtual Ponuda Ponuda { get; set; }
    }
}
